version: "3"
services:
    mysql:
        container_name: mysql
        image: mysql:5.7.25
        command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        restart: always
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: "test123"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "test123"
            MYSQL_DATABASE: "test"
        volumes:
            - /home/docker/lims_mysql:/var/lib/mysql
        resources:
        limits:
            cpus: "0.50"
            memory: 1024M
        reservations:
            cpus: "0.25"
            memory: 1024M
        ports:
            - "3307:3306"
    redis:
        container_name: redis
        image: redis:5.0.3
        command: redis-server --requirepass test123
        restart: always
        privileged: true
        volumes:
            - /home/docker/lims_redis:/data
        ports:
            - "6380:6379"
    nginx:
        container_name: nginx
        image: registry.cn-hangzhou.aliyuncs.com/pangxiaobo/lims:v1
        restart: always
        privileged: true
        links:
            - mysql
            - redis
        volumes:
            - /home/docker/lims_nginx:/var/www/app
        ports:
            - "9800:80"
            - "9701:9701"
            - "9702:9702"
            - "9703:9703"
            - "20122:22"
