version: "3"
services:
    # MySQL 5.7: https://hub.docker.com/_/mysql/
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: "pang123"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "pang123"
            #MYSQL_DATABASE: "test"
        volumes:
            #- /home/docker/mysql:/var/lib/mysql
            - /Users/xiaobopang/Downloads/personal/docker/mysql:/var/lib/mysql
        ports:
            - "13306:3306"

    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10
        restart: always
        privileged: true
        volumes:
            #- /home/docker/redis:/data
            - /Users/xiaobopang/Downloads/personal/docker/redis:/data
        ports:
            - "16379:6379"

    #内网 registry-internal.cn-hangzhou.aliyuncs.com/pangxiaobo/docker_phalcon:v1
    phalcon:
        container_name: phalcon
        image: registry.cn-hangzhou.aliyuncs.com/pangxiaobo/docker_phalcon:v1
        restart: always
        privileged: true
        links:
            - mysql
            - redis
            - nginx
        volumes:
            #- /home/docker_user/peter:/home
            - /Users/xiaobopang/Downloads/personal/docker/phalcon:/var/www/app
        ports: 
            - "10191:9091"
            - "10192:9092"
            - "10193:9093"
            - "10122:22"
    nginx:
        container_name: nginx
        image: nginx
        restart: always
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./web/index.html:/var/nginx/app/index.html:ro
            - /Users/xiaobopang/Downloads/personal/docker/nginx:/var/www/app
        ports:
            - 8081:80
            - 8082:8082
            - 8083:8083
            - 8084:8084
            - 8085:8085
            - 8086:8086
            - 10443:443