version: "3"
services:
    lims_mysql:
        container_name: lims_mysql
        image: mysql:8.0
        command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        restart: always
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: "lims_mysql"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "lims_mysql"
            MYSQL_DATABASE: "lims_hk"
        volumes:
            #- /home/docker/mysql:/var/lib/mysql
            - /Users/xiaobopang/Downloads/personal/docker/lims_mysql:/var/lib/mysql
        ports:
            - "3307:3306"
    lims_redis:
        container_name: lims_redis
        image: redis:5.0
        command: redis-server --requirepass lims_redis
        restart: always
        privileged: true
        volumes:
            - /Users/xiaobopang/Downloads/personal/docker/lims_redis:/data
        ports:
            - "6380:6379"
    lims:
        container_name: lims
        image: registry.cn-hangzhou.aliyuncs.com/pangxiaobo/php7_nginx:v1
        restart: always
        privileged: true
        links:
            - mysql
            - redis
        volumes:
            #- /home/docker_user/pang:/home
            - /Users/xiaobopang/Downloads/personal/docker/lims:/home/lims
        ports: 
            - "8081:80"
            - "9701:9703"
            - "9702:9703"
            - "9703:9703"
            - "10443:443"
            - "10122:22"